# Generated by Django 5.2 on 2025-04-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('quiz_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('time_taken', models.FloatField(help_text='Time in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
