# Generated by Django 5.2 on 2025-04-27 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='time_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('quiz_category', models.CharField(choices=[('science', 'Science'), ('math', 'Math'), ('history', 'History'), ('sports', 'Sports'), ('technology', 'Technology'), ('gk', 'General Knowledge')], default='general', max_length=50)),
                ('quiz_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('quiz_time', models.PositiveIntegerField(help_text='Time to complete the quiz in seconds')),
                ('quiz_description', models.CharField(max_length=250)),
                ('quiz_image', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz_made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
