# Generated by Django 5.2 on 2025-04-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquiz', '0002_quizresult_time_response_quizresult_user_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='rating_by_user',
            field=models.IntegerField(default=0),
        ),
    ]
