# Generated by Django 5.2 on 2025-04-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquiz', '0003_quizresult_rating_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
