# Generated by Django 5.2 on 2025-04-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquiz', '0004_alter_quiz_quiz_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_category',
            field=models.CharField(choices=[('science', 'Science'), ('math', 'Math'), ('history', 'History'), ('sports', 'Sports'), ('technology', 'Technology'), ('general knowledge', 'General Knowledge')], default='general', max_length=50),
        ),
    ]
